# Generated by Django 3.1 on 2021-02-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csvs', verbose_name='')),
                ('uploaded', models.DateField(auto_now_add=True, verbose_name='')),
                ('activated', models.BooleanField(default=False, verbose_name='')),
            ],
        ),
    ]
