# Generated by Django 3.1 on 2021-02-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210203_1914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
